"""Baseline immuable du schéma GSIE v6.2 au 2026-07-26.

Cette révision remplace l'historique local non publié 0001-0013 sur décision
du Fondateur (DEC-000036). Elle crée le schéma courant en une seule traversée
et ne dépend d'aucun modèle applicatif importé à l'exécution.

Tables applicatives : 116.
Empreinte SHA-256 du DDL upgrade : ef88ae29ddd1b3f6e6be02d65400a9a13f0bef8015c7bff4d34502b1a5157311.

Revision ID: 20260726_0001
Revises: aucune — nouvelle baseline
Create Date: 2026-07-26
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260726_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SCHEMA_FINGERPRINT = "ef88ae29ddd1b3f6e6be02d65400a9a13f0bef8015c7bff4d34502b1a5157311"

_UPGRADE_STATEMENTS: tuple[str, ...] = (
    "CREATE TYPE claim_kind AS ENUM ('observation', 'relation', 'rule', 'threshold', 'model', 'classification', 'absence')",
    "CREATE TYPE lifecycle_status AS ENUM ('draft', 'proposed', 'accepted', 'superseded', 'rejected', 'deprecated')",
    "CREATE TYPE rule_subtype AS ENUM ('inference', 'scientific', 'business', 'regulatory')",
    "CREATE TYPE participant_role AS ENUM ('subject', 'object', 'context')",
    "CREATE TYPE evidence_level AS ENUM ('A', 'B', 'C', 'D', 'E', 'F')",
    "CREATE TYPE management_plan_type AS ENUM ('psg', 'amf', 'rtg', 'custom')",
    "CREATE TYPE plan_status AS ENUM ('draft', 'submitted', 'approved', 'active', 'revision', 'expired', 'cancelled')",
    "CREATE TYPE intervention_type AS ENUM ('planting', 'thinning', 'clear_cut', 'selective_cut', 'shelterwood', 'coppicing', 'pruning', 'clearing', 'fertilization', 'drainage', 'road_work', 'protection', 'inventory', 'other')",
    "CREATE TYPE intervention_status AS ENUM ('planned', 'scheduled', 'in_progress', 'completed', 'cancelled', 'delayed')",
    "CREATE TYPE economic_category AS ENUM ('cost', 'revenue', 'subsidy', 'investment', 'market_price')",
    "CREATE TYPE regulation_domain AS ENUM ('forest_code', 'psg_obligations', 'natura_2000', 'water_protection', 'biodiversity_protection', 'urban_planning', 'environmental_impact', 'other')",
    "CREATE TYPE compliance_status AS ENUM ('compliant', 'non_compliant', 'pending_check', 'waiver', 'not_applicable')",
    "CREATE TYPE outcome_status AS ENUM ('pending', 'in_progress', 'achieved', 'partially_achieved', 'not_achieved', 'abandoned')",
    "CREATE TYPE administrative_level AS ENUM ('national', 'regional', 'departmental', 'forest_domain', 'triage', 'canton', 'parcel', 'series')",
    "CREATE TYPE diagnostic_type AS ENUM ('stationnel', 'sylvicole', 'sanitaire', 'global')",
    "CREATE TYPE diagnostic_global_state AS ENUM ('sain', 'vigueur_reduite', 'deperissement', 'critique')",
    "CREATE TYPE diagnostic_validation_status AS ENUM ('brouillon', 'valide', 'refuse')",
    "CREATE TYPE flow_type AS ENUM ('carbon', 'water', 'nitrogen', 'phosphorus', 'nutrient', 'energy', 'seed', 'pollen', 'gene', 'pathogen', 'spore', 'biomass', 'sediment', 'other')",
    "CREATE TYPE flow_direction AS ENUM ('source_to_sink', 'bidirectional')",
    "CREATE TYPE propagation_method AS ENUM ('bayesian', 'weighted_average', 'dempster_shafer', 'fuzzy')",
    "CREATE TYPE goal_type AS ENUM ('biodiversity', 'production', 'risk_reduction', 'conservation', 'restoration', 'carbon_sequestration', 'water_protection', 'soil_protection', 'recreation', 'research', 'regulatory', 'other')",
    "CREATE TYPE goal_priority AS ENUM ('primary', 'secondary', 'tertiary')",
    "CREATE TYPE constraint_type AS ENUM ('regulatory', 'budget', 'accessibility', 'weather', 'equipment', 'ecological', 'temporal', 'social', 'technical', 'other')",
    "CREATE TYPE constraint_severity AS ENUM ('blocking', 'limiting', 'conditional')",
    "CREATE TYPE terrain_session_type AS ENUM ('inventory', 'martelage', 'monitoring', 'diagnosis', 'research', 'calibration')",
    "CREATE TYPE sync_status AS ENUM ('synced', 'partial', 'pending', 'failed')",
    "CREATE TYPE state_type AS ENUM ('health', 'vitality', 'risk', 'resilience', 'biodiversity', 'productivity', 'integrity')",
    "CREATE TYPE ecological_grade AS ENUM ('excellent', 'good', 'moderate', 'poor', 'critical')",
    "CREATE TYPE trend AS ENUM ('improving', 'stable', 'declining', 'unknown')",
    "CREATE TYPE ecosystem_service_category AS ENUM ('regulation', 'support', 'provisioning', 'cultural')",
    "CREATE TYPE scale_level AS ENUM ('leaf', 'tree', 'plot', 'stand', 'forest', 'massif', 'landscape', 'region', 'country', 'biome', 'earth')",
    "CREATE TYPE phenomenon_type AS ENUM ('drought', 'storm', 'pest_outbreak', 'pathogen_outbreak', 'wildfire', 'flood', 'succession', 'migration', 'competition', 'invasion', 'decline', 'regeneration', 'phenology_shift', 'other')",
    "CREATE TYPE ecological_process_type AS ENUM ('photosynthesis', 'transpiration', 'respiration', 'growth', 'decomposition', 'nutrient_cycling', 'mycorrhization', 'nitrogen_fixation', 'pollination', 'seed_dispersal', 'herbivory', 'predation', 'competition', 'facilitation', 'succession', 'carbon_sequestration', 'water_cycling', 'other')",
    "CREATE TYPE relation_category AS ENUM ('causal', 'spatial', 'temporal', 'ecological', 'taxonomic', 'hydrological', 'genetic', 'trophic', 'competition', 'facilitation', 'host_pathogen', 'predator_prey', 'other')",
    "CREATE TYPE sample_type AS ENUM ('soil', 'leaf', 'bark', 'wood_core', 'water', 'root', 'seed', 'tissue', 'soil_water', 'litter', 'other')",
    "CREATE TYPE consent_scope AS ENUM ('full', 'anonymized_only', 'aggregated_only')",
    "CREATE TYPE legal_basis AS ENUM ('consent', 'contract', 'legal_obligation', 'vital_interest', 'public_interest', 'legitimate_interest', 'research')",
    "CREATE TYPE pid_type AS ENUM ('doi', 'purl', 'orcid', 'ror', 'gbif_taxonkey', 'wikidata_qid', 'inpn_taxref', 'issn', 'handle', 'ark', 'urn', 'gsie_uri')",
    "CREATE TYPE silvicultural_system_category AS ENUM ('futaie_reguliere', 'futaie_irreguliere', 'taillis', 'taillis_sous_futaie', 'conversion', 'autre')",
    "CREATE TYPE health_risk_severity AS ENUM ('negligible', 'low', 'moderate', 'high', 'critical')",
    "CREATE TYPE materiel_base_category AS ENUM ('identifie', 'selectionne', 'qualifie', 'teste')",
    "CREATE TYPE usage_rights AS ENUM ('open', 'restricted', 'private')",
    "CREATE TYPE permission AS ENUM ('read', 'write', 'delete', 'export', 'admin')",
    "CREATE TYPE sensitivity_level AS ENUM ('public', 'restricted', 'sensitive', 'critical')",
    "CREATE TYPE conflict_status AS ENUM ('open', 'resolved_by_consensus', 'resolved_by_arbitrage', 'unresolved')",
    "CREATE TYPE identification_decision_status AS ENUM ('suggestion_ia', 'validee_utilisateur', 'rejetee')",
    "CREATE TYPE model_type AS ENUM ('growth', 'dynamics', 'propagation', 'climate', 'ml')",
    "CREATE TYPE dataset_purpose AS ENUM ('production', 'training', 'evaluation', 'reference')",
    "CREATE TYPE access_method AS ENUM ('api_rest', 'api_graphql', 'ogc_wms', 'ogc_wfs', 'ogc_wmts', 'ogc_wcs', 'stac_api', 'file_download', 'file_import', 'publication_text', 'knowledge_extraction')",
    "CREATE TYPE feature_source_type AS ENUM ('observation', 'trait', 'computed', 'external')",
    "CREATE TYPE value_type AS ENUM ('numeric', 'term', 'media_ref', 'entity_ref', 'computed', 'absence')",
    "CREATE TYPE uncertainty_type AS ENUM ('confidence_interval', 'standard_error', 'range', 'qualitative')",
    "CREATE TYPE quality_dimension AS ENUM ('completeness', 'positional_accuracy', 'temporal_accuracy', 'thematic_accuracy', 'logical_consistency')",
    "CREATE TYPE activity_type AS ENUM ('extraction', 'transformation', 'ingestion', 'validation', 'revision', 'simulation')",
    "CREATE TYPE agent_type AS ENUM ('person', 'organisation', 'software')",
    "CREATE TYPE source_subtype AS ENUM ('publication', 'dataset', 'api', 'person', 'organisation', 'regulatory_text', 'expert_statement')",
    "CREATE TYPE source_nature AS ENUM ('data_provider', 'knowledge_provider', 'reference', 'expert_statement', 'regulatory', 'model_output')",
    "CREATE TYPE citation_role AS ENUM ('primary', 'supporting', 'contradicting', 'cited')",
    "CREATE TYPE question_type AS ENUM ('scientific', 'operational', 'diagnostic', 'predictive')",
    "CREATE TYPE hypothesis_status AS ENUM ('proposed', 'testing', 'supported', 'refuted', 'inconclusive')",
    "CREATE TYPE scenario_type AS ENUM ('sylvicultural', 'climatic', 'management', 'disturbance', 'baseline')",
    "CREATE TYPE scenario_subtype AS ENUM ('rcp_2_6', 'rcp_4_5', 'rcp_8_5', 'ssp1_2_6', 'ssp3_7_0', 'ssp5_8_5', 'drias_2020', 'clear_cut', 'selective_thinning', 'shelterwood', 'coppice', 'no_intervention', 'adaptive', 'wildfire', 'storm', 'pest_outbreak', 'baseline')",
    "CREATE TYPE correlation_method AS ENUM ('pearson', 'spearman', 'kendall', 'bayesian', 'mutual_information', 'ai', 'expert', 'literature', 'meta_analysis')",
    "CREATE TYPE correlation_strength AS ENUM ('negligible', 'weak', 'moderate', 'strong', 'very_strong')",
    "CREATE TYPE capability_type AS ENUM ('observe', 'predict', 'inventory', 'diagnose', 'simulate', 'recommend', 'correlate', 'reason', 'validate', 'learn', 'extract', 'assess_evidence')",
    "CREATE TYPE provider_type AS ENUM ('engine', 'application')",
    "CREATE TYPE temporal_granularity AS ENUM ('instant', 'day', 'month', 'year', 'period', 'range')",
    "CREATE TYPE media_type AS ENUM ('image', 'audio', 'video', 'document')",
    "CREATE TABLE resource (\n\tid UUID NOT NULL, \n\ttype VARCHAR(50) NOT NULL, \n\tgsie_id VARCHAR(100), \n\tmetadata_json JSONB NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE INDEX ix_resource_type ON resource (type)",
    "CREATE UNIQUE INDEX ix_resource_gsie_id ON resource (gsie_id)",
    "CREATE TABLE outbox_event (\n\tid UUID NOT NULL, \n\taggregate_id UUID NOT NULL, \n\taggregate_type VARCHAR(50) NOT NULL, \n\tevent_type VARCHAR(100) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tstatus VARCHAR(20) NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE INDEX ix_outbox_event_aggregate_id ON outbox_event (aggregate_id)",
    "CREATE INDEX ix_outbox_event_aggregate_type ON outbox_event (aggregate_type)",
    "CREATE INDEX ix_outbox_event_event_type ON outbox_event (event_type)",
    "CREATE INDEX ix_outbox_event_status ON outbox_event (status)",
    "CREATE INDEX ix_outbox_status_created ON outbox_event (status, created_at)",
    "CREATE TABLE inbox_event (\n\tid UUID NOT NULL, \n\tsource VARCHAR(100) NOT NULL, \n\texternal_id VARCHAR(200) NOT NULL, \n\tevent_type VARCHAR(100) NOT NULL, \n\tpayload JSONB NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, \n\tprocessed_at TIMESTAMP WITH TIME ZONE, \n\tstatus VARCHAR(20) NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "CREATE INDEX ix_inbox_event_event_type ON inbox_event (event_type)",
    "CREATE INDEX ix_inbox_event_source ON inbox_event (source)",
    "CREATE INDEX ix_inbox_event_status ON inbox_event (status)",
    "CREATE UNIQUE INDEX ix_inbox_source_external ON inbox_event (source, external_id)",
    "CREATE TABLE assertion (\n\tid UUID NOT NULL, \n\tclaim_kind claim_kind NOT NULL, \n\tlifecycle_status lifecycle_status NOT NULL, \n\trule_subtype rule_subtype, \n\tpredicate_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\tversion INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(predicate_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_assertion_claim_kind ON assertion (claim_kind)",
    "CREATE INDEX ix_assertion_lifecycle_status ON assertion (lifecycle_status)",
    "CREATE INDEX ix_assertion_predicate_id ON assertion (predicate_id)",
    "CREATE TABLE assertion_participant (\n\tid SERIAL NOT NULL, \n\tassertion_id UUID NOT NULL, \n\trole participant_role NOT NULL, \n\tparticipant_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(participant_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_assertion_participant_assertion_id ON assertion_participant (assertion_id)",
    "CREATE INDEX ix_assertion_participant_participant_id ON assertion_participant (participant_id)",
    "CREATE TABLE assertion_qualifier (\n\tid SERIAL NOT NULL, \n\tassertion_id UUID NOT NULL, \n\tkey VARCHAR(100) NOT NULL, \n\tvalue TEXT NOT NULL, \n\tunit_id UUID, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(unit_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_assertion_qualifier_assertion_id ON assertion_qualifier (assertion_id)",
    "CREATE TABLE predicate (\n\tid UUID NOT NULL, \n\tlabel VARCHAR(200) NOT NULL, \n\tinverse_label VARCHAR(200), \n\tcontrolled_term_id UUID, \n\trelation_type_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(controlled_term_id) REFERENCES resource (id), \n\tFOREIGN KEY(relation_type_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_predicate_label ON predicate (label)",
    "CREATE INDEX ix_predicate_relation_type_id ON predicate (relation_type_id)",
    "CREATE TABLE evidence_assessment (\n\tid UUID NOT NULL, \n\tassertion_id UUID NOT NULL, \n\tlevel evidence_level NOT NULL, \n\tevaluator_id UUID, \n\tmethod VARCHAR(200) NOT NULL, \n\tevaluated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tscope TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id), \n\tFOREIGN KEY(evaluator_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_evidence_assessment_assertion_id ON evidence_assessment (assertion_id)",
    "CREATE INDEX ix_evidence_assessment_level ON evidence_assessment (level)",
    "CREATE TABLE management_plan (\n\tid UUID NOT NULL, \n\tplan_type management_plan_type NOT NULL, \n\tstatus plan_status NOT NULL, \n\tspatial_scope_id UUID NOT NULL, \n\towner_id UUID, \n\tmanager_id UUID, \n\tstart_date DATE NOT NULL, \n\tend_date DATE NOT NULL, \n\trevision_number INTEGER NOT NULL, \n\tapproval_date DATE, \n\tapproval_authority VARCHAR(200), \n\tobjectives JSONB NOT NULL, \n\tsummary TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(owner_id) REFERENCES resource (id), \n\tFOREIGN KEY(manager_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_management_plan_manager_id ON management_plan (manager_id)",
    "CREATE INDEX ix_management_plan_owner_id ON management_plan (owner_id)",
    "CREATE INDEX ix_management_plan_plan_type ON management_plan (plan_type)",
    "CREATE INDEX ix_management_plan_spatial_scope_id ON management_plan (spatial_scope_id)",
    "CREATE INDEX ix_management_plan_status ON management_plan (status)",
    "CREATE TABLE intervention (\n\tid UUID NOT NULL, \n\tintervention_type intervention_type NOT NULL, \n\tstatus intervention_status NOT NULL, \n\tplan_id UUID, \n\tspatial_scope_id UUID NOT NULL, \n\tscheduled_date DATE, \n\tcompleted_date DATE, \n\tarea_ha FLOAT, \n\tvolume_m3 FLOAT, \n\ttarget_species JSONB NOT NULL, \n\toperator_id UUID, \n\tnotes TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(plan_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(operator_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_intervention_intervention_type ON intervention (intervention_type)",
    "CREATE INDEX ix_intervention_plan_id ON intervention (plan_id)",
    "CREATE INDEX ix_intervention_spatial_scope_id ON intervention (spatial_scope_id)",
    "CREATE INDEX ix_intervention_status ON intervention (status)",
    "CREATE TABLE economic_scenario (\n\tid UUID NOT NULL, \n\tcategory economic_category NOT NULL, \n\tplan_id UUID, \n\tintervention_id UUID, \n\tamount_eur FLOAT NOT NULL, \n\tyear INTEGER, \n\tunit VARCHAR(50), \n\tdescription TEXT, \n\tsource_reference VARCHAR(500), \n\tdetails JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(plan_id) REFERENCES resource (id), \n\tFOREIGN KEY(intervention_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_economic_scenario_category ON economic_scenario (category)",
    "CREATE INDEX ix_economic_scenario_intervention_id ON economic_scenario (intervention_id)",
    "CREATE INDEX ix_economic_scenario_plan_id ON economic_scenario (plan_id)",
    "CREATE TABLE regulation (\n\tid UUID NOT NULL, \n\tdomain regulation_domain NOT NULL, \n\tcode VARCHAR(100) NOT NULL, \n\ttitle VARCHAR(500) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tauthority VARCHAR(200), \n\teffective_date DATE, \n\turl VARCHAR(500), \n\tpenalties JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_regulation_code ON regulation (code)",
    "CREATE INDEX ix_regulation_domain ON regulation (domain)",
    "CREATE TABLE compliance_check (\n\tid UUID NOT NULL, \n\tregulation_id UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tstatus compliance_status NOT NULL, \n\tchecked_by UUID, \n\tchecked_at TIMESTAMP WITH TIME ZONE, \n\tdetails TEXT, \n\twaiver_reason TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(regulation_id) REFERENCES resource (id), \n\tFOREIGN KEY(target_id) REFERENCES resource (id), \n\tFOREIGN KEY(checked_by) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_compliance_check_regulation_id ON compliance_check (regulation_id)",
    "CREATE INDEX ix_compliance_check_status ON compliance_check (status)",
    "CREATE INDEX ix_compliance_check_target_id ON compliance_check (target_id)",
    "CREATE TABLE outcome_tracking (\n\tid UUID NOT NULL, \n\trecommendation_id UUID NOT NULL, \n\tdecision_id UUID, \n\tstatus outcome_status NOT NULL, \n\texpected_outcome TEXT NOT NULL, \n\tactual_outcome TEXT, \n\texpected_date DATE, \n\tactual_date DATE, \n\tassessment TEXT, \n\tmetrics JSONB NOT NULL, \n\trecalibration_notes TEXT, \n\tfeedback_score FLOAT, \n\tlessons_learned TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(recommendation_id) REFERENCES resource (id), \n\tFOREIGN KEY(decision_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_outcome_tracking_decision_id ON outcome_tracking (decision_id)",
    "CREATE INDEX ix_outcome_tracking_recommendation_id ON outcome_tracking (recommendation_id)",
    "CREATE INDEX ix_outcome_tracking_status ON outcome_tracking (status)",
    "CREATE TABLE administrative_unit (\n\tid UUID NOT NULL, \n\tlevel administrative_level NOT NULL, \n\tcode VARCHAR(100) NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tparent_id UUID, \n\tspatial_scope_id UUID, \n\tauthority VARCHAR(200), \n\tattributes JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(parent_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_administrative_unit_code ON administrative_unit (code)",
    "CREATE INDEX ix_administrative_unit_level ON administrative_unit (level)",
    "CREATE INDEX ix_administrative_unit_parent_id ON administrative_unit (parent_id)",
    "CREATE INDEX ix_administrative_unit_spatial_scope_id ON administrative_unit (spatial_scope_id)",
    "CREATE TABLE diagnostic (\n\tid UUID NOT NULL, \n\trequete_origine UUID NOT NULL, \n\tstation_id UUID NOT NULL, \n\ttype_diagnostic diagnostic_type NOT NULL, \n\tetat_global diagnostic_global_state NOT NULL, \n\tstatut_validation diagnostic_validation_status NOT NULL, \n\tconfiance FLOAT NOT NULL, \n\tevidence_level_plancher evidence_level NOT NULL, \n\tdate_diagnostic TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcontenu JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_diagnostic_date_diagnostic ON diagnostic (date_diagnostic)",
    "CREATE INDEX ix_diagnostic_etat_global ON diagnostic (etat_global)",
    "CREATE INDEX ix_diagnostic_requete_origine ON diagnostic (requete_origine)",
    "CREATE INDEX ix_diagnostic_station_date ON diagnostic (station_id, date_diagnostic)",
    "CREATE INDEX ix_diagnostic_station_id ON diagnostic (station_id)",
    "CREATE INDEX ix_diagnostic_statut_validation ON diagnostic (statut_validation)",
    "CREATE INDEX ix_diagnostic_type_diagnostic ON diagnostic (type_diagnostic)",
    "CREATE TABLE flow (\n\tid UUID NOT NULL, \n\tflow_type flow_type NOT NULL, \n\tsource_id UUID NOT NULL, \n\tsink_id UUID NOT NULL, \n\tmagnitude FLOAT NOT NULL, \n\tmagnitude_unit_id UUID NOT NULL, \n\tdirection flow_direction NOT NULL, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\tdriver_process_id UUID, \n\tuncertainty_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_id) REFERENCES resource (id), \n\tFOREIGN KEY(sink_id) REFERENCES resource (id), \n\tFOREIGN KEY(magnitude_unit_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(driver_process_id) REFERENCES resource (id), \n\tFOREIGN KEY(uncertainty_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_flow_flow_type ON flow (flow_type)",
    "CREATE INDEX ix_flow_sink_id ON flow (sink_id)",
    "CREATE INDEX ix_flow_source_id ON flow (source_id)",
    "CREATE TABLE goal (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tgoal_type goal_type NOT NULL, \n\tdescription TEXT NOT NULL, \n\tpriority goal_priority NOT NULL, \n\ttarget_value FLOAT, \n\tparent_goal_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\tsuccess_criteria TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(parent_goal_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_goal_goal_type ON goal (goal_type)",
    "CREATE INDEX ix_goal_name ON goal (name)",
    'CREATE TABLE "constraint" (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tconstraint_type constraint_type NOT NULL, \n\tdescription TEXT NOT NULL, \n\tseverity constraint_severity NOT NULL, \n\tsource_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\taffected_recommendation_id UUID, \n\tmitigation TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(affected_recommendation_id) REFERENCES resource (id)\n)',
    'CREATE INDEX ix_constraint_constraint_type ON "constraint" (constraint_type)',
    'CREATE INDEX ix_constraint_name ON "constraint" (name)',
    "CREATE TABLE knowledge_lineage (\n\tid UUID NOT NULL, \n\tresource_id UUID NOT NULL, \n\tproduced_by UUID, \n\tproduction_method VARCHAR(50), \n\tconfidence_graph_id UUID, \n\tlineage_depth INTEGER NOT NULL, \n\tcomputed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(resource_id) REFERENCES resource (id), \n\tFOREIGN KEY(produced_by) REFERENCES resource (id), \n\tFOREIGN KEY(confidence_graph_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_knowledge_lineage_production_method ON knowledge_lineage (production_method)",
    "CREATE INDEX ix_knowledge_lineage_resource_id ON knowledge_lineage (resource_id)",
    "CREATE TABLE experiment (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\thypothesis_id UUID, \n\tcomparison_metrics JSONB NOT NULL, \n\tconclusion TEXT, \n\tresulting_assertion_id UUID, \n\tresulting_source_id UUID, \n\tconducted_by UUID NOT NULL, \n\tscale_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(hypothesis_id) REFERENCES resource (id), \n\tFOREIGN KEY(resulting_assertion_id) REFERENCES resource (id), \n\tFOREIGN KEY(resulting_source_id) REFERENCES resource (id), \n\tFOREIGN KEY(conducted_by) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_experiment_name ON experiment (name)",
    "CREATE TABLE terrain_session (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tsession_type terrain_session_type NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\toperator_id UUID, \n\tweather JSONB, \n\tgps_precision_m FLOAT, \n\tequipment JSONB NOT NULL, \n\tspatial_scope_id UUID, \n\tscale_context_id UUID, \n\tprotocol_id UUID, \n\tsync_status sync_status NOT NULL, \n\tnotes TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(operator_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(protocol_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_terrain_session_name ON terrain_session (name)",
    "CREATE INDEX ix_terrain_session_session_type ON terrain_session (session_type)",
    "CREATE TABLE ecological_state (\n\tid UUID NOT NULL, \n\tspatial_scope_id UUID NOT NULL, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\tstate_type state_type NOT NULL, \n\tindicators JSONB NOT NULL, \n\toverall_score FLOAT, \n\toverall_grade ecological_grade, \n\tcomputed_by UUID, \n\ttrend trend, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(computed_by) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_ecological_state_spatial_scope_id ON ecological_state (spatial_scope_id)",
    "CREATE INDEX ix_ecological_state_state_type ON ecological_state (state_type)",
    "CREATE TABLE ecosystem_service (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tcategory ecosystem_service_category NOT NULL, \n\tdescription TEXT NOT NULL, \n\tspatial_scope_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_ecosystem_service_category ON ecosystem_service (category)",
    "CREATE INDEX ix_ecosystem_service_name ON ecosystem_service (name)",
    "CREATE TABLE scale_context (\n\tid UUID NOT NULL, \n\tlevel scale_level NOT NULL, \n\tparent_scale_id UUID, \n\textent_m2 FLOAT, \n\tgrain_m2 FLOAT, \n\tdescription TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(parent_scale_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_scale_context_level ON scale_context (level)",
    "CREATE TABLE phenomenon (\n\tid UUID NOT NULL, \n\tphenomenon_type phenomenon_type NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tintensity FLOAT, \n\tintensity_unit_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(intensity_unit_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_phenomenon_phenomenon_type ON phenomenon (phenomenon_type)",
    "CREATE TABLE ecological_process (\n\tid UUID NOT NULL, \n\tprocess_type ecological_process_type NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\trate FLOAT, \n\trate_unit_id UUID, \n\tdriver_phenomenon_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(rate_unit_id) REFERENCES resource (id), \n\tFOREIGN KEY(driver_phenomenon_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_ecological_process_process_type ON ecological_process (process_type)",
    "CREATE TABLE relation_type (\n\tid UUID NOT NULL, \n\tcategory relation_category NOT NULL, \n\tlabel VARCHAR(200) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tparent_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(parent_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_relation_type_category ON relation_type (category)",
    "CREATE TABLE sampling_event (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tprotocol_id UUID, \n\tspatial_design TEXT NOT NULL, \n\ttemporal_context_id UUID, \n\tscale_context_id UUID, \n\tparent_event_id UUID, \n\tprincipal_investigator_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(protocol_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(parent_event_id) REFERENCES resource (id), \n\tFOREIGN KEY(principal_investigator_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_sampling_event_name ON sampling_event (name)",
    "CREATE TABLE trait_definition (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tabbreviation VARCHAR(20), \n\tdescription TEXT NOT NULL, \n\tunit_id UUID, \n\tstandard_reference VARCHAR(100), \n\tvalue_range VARCHAR(100), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(unit_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_trait_definition_name ON trait_definition (name)",
    "CREATE TABLE trait_value (\n\tid UUID NOT NULL, \n\ttrait_definition_id UUID NOT NULL, \n\tentity_id UUID NOT NULL, \n\tvalue_numeric FLOAT, \n\tvalue_term_id UUID, \n\tunit_id UUID, \n\tuncertainty_id UUID, \n\tobservation_id UUID, \n\tscale_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(trait_definition_id) REFERENCES resource (id), \n\tFOREIGN KEY(entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(value_term_id) REFERENCES resource (id), \n\tFOREIGN KEY(unit_id) REFERENCES resource (id), \n\tFOREIGN KEY(uncertainty_id) REFERENCES resource (id), \n\tFOREIGN KEY(observation_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_trait_value_entity_id ON trait_value (entity_id)",
    "CREATE INDEX ix_trait_value_trait_definition_id ON trait_value (trait_definition_id)",
    "CREATE TABLE sample (\n\tid UUID NOT NULL, \n\tsample_type sample_type NOT NULL, \n\tsampling_event_id UUID, \n\tsubject_id UUID NOT NULL, \n\tmaterial VARCHAR(100) NOT NULL, \n\tstorage_location VARCHAR(200), \n\tstorage_conditions VARCHAR(200), \n\tcollected_at UUID, \n\tmass_g FLOAT, \n\tvolume_ml FLOAT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(sampling_event_id) REFERENCES resource (id), \n\tFOREIGN KEY(subject_id) REFERENCES resource (id), \n\tFOREIGN KEY(collected_at) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_sample_sample_type ON sample (sample_type)",
    "CREATE INDEX ix_sample_subject_id ON sample (subject_id)",
    "CREATE TABLE consent (\n\tid UUID NOT NULL, \n\tdata_subject_id UUID NOT NULL, \n\tpurpose TEXT NOT NULL, \n\tscope consent_scope NOT NULL, \n\tgranted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\twithdrawn_at TIMESTAMP WITH TIME ZONE, \n\tlegal_basis legal_basis NOT NULL, \n\tdocument_ref VARCHAR(500), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(data_subject_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_consent_data_subject_id ON consent (data_subject_id)",
    "CREATE INDEX ix_consent_legal_basis ON consent (legal_basis)",
    "CREATE TABLE data_subject (\n\tid UUID NOT NULL, \n\tagent_id UUID NOT NULL, \n\tpseudonymized_id VARCHAR(200) NOT NULL, \n\temail_encrypted VARCHAR(500), \n\tanonymized BOOLEAN NOT NULL, \n\trights_exercised JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(agent_id) REFERENCES resource (id), \n\tUNIQUE (pseudonymized_id)\n)",
    "CREATE INDEX ix_data_subject_agent_id ON data_subject (agent_id)",
    "CREATE TABLE persistent_identifier (\n\tid UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tpid_type pid_type NOT NULL, \n\tvalue VARCHAR(500) NOT NULL, \n\tauthority VARCHAR(100) NOT NULL, \n\tregistered_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(target_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_persistent_identifier_pid_type ON persistent_identifier (pid_type)",
    "CREATE INDEX ix_persistent_identifier_target_id ON persistent_identifier (target_id)",
    "CREATE INDEX ix_persistent_identifier_value ON persistent_identifier (value)",
    "CREATE TABLE autecology_profile (\n\tid UUID NOT NULL, \n\tspecies_entity_id UUID NOT NULL, \n\tvariable VARCHAR(200) NOT NULL, \n\tvalue_numeric FLOAT, \n\tvalue_text TEXT, \n\tunit VARCHAR(50), \n\tlife_stage VARCHAR(100), \n\tseason VARCHAR(50), \n\tterritory_description TEXT, \n\tmethod TEXT, \n\tuncertainty TEXT, \n\tevidence_level evidence_level NOT NULL, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_autecology_profile_value_present CHECK (value_numeric IS NOT NULL OR value_text IS NOT NULL), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(species_entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_autecology_profile_source_id ON autecology_profile (source_id)",
    "CREATE INDEX ix_autecology_profile_species_entity_id ON autecology_profile (species_entity_id)",
    "CREATE INDEX ix_autecology_profile_variable ON autecology_profile (variable)",
    "CREATE TABLE site_index_model (\n\tid UUID NOT NULL, \n\tspecies_entity_id UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tmethod VARCHAR(200) NOT NULL, \n\treference_age_years INTEGER NOT NULL, \n\tage_convention VARCHAR(200) NOT NULL, \n\tcalibration_region VARCHAR(200) NOT NULL, \n\tvalid_age_min_years INTEGER, \n\tvalid_age_max_years INTEGER, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_site_index_model_valid_age_range CHECK (valid_age_min_years IS NULL OR valid_age_max_years IS NULL OR valid_age_min_years <= valid_age_max_years), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(species_entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_site_index_model_source_id ON site_index_model (source_id)",
    "CREATE INDEX ix_site_index_model_species_entity_id ON site_index_model (species_entity_id)",
    "CREATE TABLE station_type (\n\tid UUID NOT NULL, \n\tguide VARCHAR(300) NOT NULL, \n\tguide_version VARCHAR(100) NOT NULL, \n\tvalidity_zone_description TEXT NOT NULL, \n\tser_greco_code VARCHAR(50), \n\ttopography_description TEXT, \n\tsubstrate_description TEXT, \n\thydromorphy_description TEXT, \n\tindicator_flora_description TEXT, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_station_type_guide ON station_type (guide)",
    "CREATE INDEX ix_station_type_ser_greco_code ON station_type (ser_greco_code)",
    "CREATE INDEX ix_station_type_source_id ON station_type (source_id)",
    "CREATE TABLE silvicultural_system (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tcategory silvicultural_system_category NOT NULL, \n\tdescription TEXT, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_silvicultural_system_category ON silvicultural_system (category)",
    "CREATE INDEX ix_silvicultural_system_name ON silvicultural_system (name)",
    "CREATE INDEX ix_silvicultural_system_source_id ON silvicultural_system (source_id)",
    "CREATE TABLE diagnostic_protocol (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tversion VARCHAR(100) NOT NULL, \n\tcriteria_description TEXT NOT NULL, \n\tthresholds_description TEXT NOT NULL, \n\tlimitations TEXT, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_diagnostic_protocol_name ON diagnostic_protocol (name)",
    "CREATE INDEX ix_diagnostic_protocol_source_id ON diagnostic_protocol (source_id)",
    "CREATE TABLE provenance_material (\n\tid UUID NOT NULL, \n\tspecies_entity_id UUID NOT NULL, \n\tprovenance_region VARCHAR(200) NOT NULL, \n\tbase_material VARCHAR(300) NOT NULL, \n\tbase_material_category materiel_base_category NOT NULL, \n\taid_eligible BOOLEAN NOT NULL, \n\tdecree_version VARCHAR(300) NOT NULL, \n\tvalid_region_description TEXT, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(species_entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_provenance_material_base_material_category ON provenance_material (base_material_category)",
    "CREATE INDEX ix_provenance_material_provenance_region ON provenance_material (provenance_region)",
    "CREATE INDEX ix_provenance_material_source_id ON provenance_material (source_id)",
    "CREATE INDEX ix_provenance_material_species_entity_id ON provenance_material (species_entity_id)",
    "CREATE TABLE rights_statement (\n\tid UUID NOT NULL, \n\tlicence VARCHAR(100) NOT NULL, \n\tusage_rights usage_rights NOT NULL, \n\tattribution_required BOOLEAN NOT NULL, \n\tai_training_allowed BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_rights_statement_licence ON rights_statement (licence)",
    "CREATE TABLE access_policy (\n\tid UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tprincipal VARCHAR(200) NOT NULL, \n\tpermission permission NOT NULL, \n\tcondition TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(target_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_access_policy_permission ON access_policy (permission)",
    "CREATE INDEX ix_access_policy_target_id ON access_policy (target_id)",
    "CREATE TABLE sensitivity_classification (\n\tid UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tlevel sensitivity_level NOT NULL, \n\treason VARCHAR(300) NOT NULL, \n\tclassified_by UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(target_id) REFERENCES resource (id), \n\tFOREIGN KEY(classified_by) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_sensitivity_classification_level ON sensitivity_classification (level)",
    "CREATE INDEX ix_sensitivity_classification_target_id ON sensitivity_classification (target_id)",
    "CREATE TABLE spatial_disclosure_policy (\n\tid UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tpublic_precision VARCHAR(50) NOT NULL, \n\trestricted_precision VARCHAR(50) NOT NULL, \n\tauthority VARCHAR(100), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(target_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_spatial_disclosure_policy_target_id ON spatial_disclosure_policy (target_id)",
    "CREATE TABLE conflict_cluster (\n\tid UUID NOT NULL, \n\tdescription TEXT NOT NULL, \n\tstatus conflict_status NOT NULL, \n\tresolution_note TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_conflict_cluster_status ON conflict_cluster (status)",
    "CREATE TABLE botanical_identification_request (\n\tid UUID NOT NULL, \n\trequested_by_id UUID NOT NULL, \n\tparcel_id UUID, \n\tphotos JSONB NOT NULL, \n\tcaptured_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsent_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(requested_by_id) REFERENCES resource (id), \n\tFOREIGN KEY(parcel_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_botanical_identification_request_parcel_id ON botanical_identification_request (parcel_id)",
    "CREATE INDEX ix_botanical_identification_request_requested_by_id ON botanical_identification_request (requested_by_id)",
    "CREATE TABLE botanical_identification_result (\n\tid UUID NOT NULL, \n\trequest_id UUID NOT NULL, \n\tprovider VARCHAR(100) NOT NULL, \n\tprovider_engine_version VARCHAR(100) NOT NULL, \n\tcandidates JSONB NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(request_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_botanical_identification_result_request_id ON botanical_identification_result (request_id)",
    "CREATE TABLE botanical_identification_decision (\n\tid UUID NOT NULL, \n\tresult_id UUID NOT NULL, \n\tstatus identification_decision_status NOT NULL, \n\tselected_candidate_index INTEGER, \n\tmanual_species_entity_id UUID, \n\tvalidated_by_id UUID, \n\tdecided_at TIMESTAMP WITH TIME ZONE, \n\trejection_reason TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_bid_validation_requires_evidence CHECK ((status != 'validee_utilisateur') OR (validated_by_id IS NOT NULL AND decided_at IS NOT NULL AND (selected_candidate_index IS NOT NULL OR manual_species_entity_id IS NOT NULL))), \n\tCONSTRAINT ck_bid_rejection_requires_validator CHECK ((status != 'rejetee') OR (validated_by_id IS NOT NULL AND decided_at IS NOT NULL)), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(result_id) REFERENCES resource (id), \n\tFOREIGN KEY(manual_species_entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(validated_by_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_botanical_identification_decision_result_id ON botanical_identification_decision (result_id)",
    "CREATE TABLE model_run_input (\n\tid SERIAL NOT NULL, \n\tmodel_run_id UUID NOT NULL, \n\tinput_id UUID NOT NULL, \n\trole VARCHAR(50), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(model_run_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(input_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_model_run_input_input ON model_run_input (input_id)",
    "CREATE INDEX ix_model_run_input_run ON model_run_input (model_run_id)",
    "CREATE TABLE model_run_output (\n\tid SERIAL NOT NULL, \n\tmodel_run_id UUID NOT NULL, \n\toutput_id UUID NOT NULL, \n\trole VARCHAR(50), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(model_run_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(output_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_model_run_output_output ON model_run_output (output_id)",
    "CREATE INDEX ix_model_run_output_run ON model_run_output (model_run_id)",
    "CREATE TABLE conflict_cluster_assertion (\n\tid SERIAL NOT NULL, \n\tconflict_cluster_id UUID NOT NULL, \n\tassertion_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conflict_cluster_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_cc_assertion_assertion ON conflict_cluster_assertion (assertion_id)",
    "CREATE INDEX ix_cc_assertion_cluster ON conflict_cluster_assertion (conflict_cluster_id)",
    "CREATE TABLE hypothesis_supporting (\n\tid SERIAL NOT NULL, \n\thypothesis_id UUID NOT NULL, \n\tassertion_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(hypothesis_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_hyp_supporting_assertion ON hypothesis_supporting (assertion_id)",
    "CREATE INDEX ix_hyp_supporting_hyp ON hypothesis_supporting (hypothesis_id)",
    "CREATE TABLE hypothesis_contradicting (\n\tid SERIAL NOT NULL, \n\thypothesis_id UUID NOT NULL, \n\tassertion_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(hypothesis_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_hyp_contradicting_assertion ON hypothesis_contradicting (assertion_id)",
    "CREATE INDEX ix_hyp_contradicting_hyp ON hypothesis_contradicting (hypothesis_id)",
    "CREATE TABLE decision_recommendation (\n\tid SERIAL NOT NULL, \n\tdecision_id UUID NOT NULL, \n\trecommendation_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(decision_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(recommendation_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_dec_rec_decision ON decision_recommendation (decision_id)",
    "CREATE INDEX ix_dec_rec_recommendation ON decision_recommendation (recommendation_id)",
    "CREATE TABLE decision_evidence (\n\tid SERIAL NOT NULL, \n\tdecision_id UUID NOT NULL, \n\tcitation_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(decision_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(citation_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_dec_evidence_citation ON decision_evidence (citation_id)",
    "CREATE INDEX ix_dec_evidence_decision ON decision_evidence (decision_id)",
    "CREATE TABLE recommendation_assertion (\n\tid SERIAL NOT NULL, \n\trecommendation_id UUID NOT NULL, \n\tassertion_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(recommendation_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assertion_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_rec_assertion_assertion ON recommendation_assertion (assertion_id)",
    "CREATE INDEX ix_rec_assertion_rec ON recommendation_assertion (recommendation_id)",
    "CREATE TABLE recommendation_scenario (\n\tid SERIAL NOT NULL, \n\trecommendation_id UUID NOT NULL, \n\tscenario_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(recommendation_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(scenario_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_rec_scenario_rec ON recommendation_scenario (recommendation_id)",
    "CREATE INDEX ix_rec_scenario_scenario ON recommendation_scenario (scenario_id)",
    "CREATE TABLE feature_set_feature (\n\tid SERIAL NOT NULL, \n\tfeature_set_id UUID NOT NULL, \n\tfeature_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(feature_set_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(feature_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_fs_feature_feature ON feature_set_feature (feature_id)",
    "CREATE INDEX ix_fs_feature_set ON feature_set_feature (feature_set_id)",
    "CREATE TABLE experiment_scenario (\n\tid SERIAL NOT NULL, \n\texperiment_id UUID NOT NULL, \n\tscenario_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(experiment_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(scenario_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_exp_scenario_exp ON experiment_scenario (experiment_id)",
    "CREATE INDEX ix_exp_scenario_scenario ON experiment_scenario (scenario_id)",
    "CREATE TABLE experiment_model_run (\n\tid SERIAL NOT NULL, \n\texperiment_id UUID NOT NULL, \n\tmodel_run_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(experiment_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(model_run_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_exp_mr_exp ON experiment_model_run (experiment_id)",
    "CREATE INDEX ix_exp_mr_model_run ON experiment_model_run (model_run_id)",
    "CREATE TABLE ecological_state_basis (\n\tid SERIAL NOT NULL, \n\tecological_state_id UUID NOT NULL, \n\tbasis_id UUID NOT NULL, \n\tbasis_type VARCHAR(50), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(ecological_state_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(basis_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_eco_state_basis_basis ON ecological_state_basis (basis_id)",
    "CREATE INDEX ix_eco_state_basis_state ON ecological_state_basis (ecological_state_id)",
    "CREATE TABLE correlation_variable (\n\tid SERIAL NOT NULL, \n\tcorrelation_id UUID NOT NULL, \n\tvariable_id UUID NOT NULL, \n\trole VARCHAR(50), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(correlation_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(variable_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_corr_var_correlation ON correlation_variable (correlation_id)",
    "CREATE INDEX ix_corr_var_variable ON correlation_variable (variable_id)",
    "CREATE TABLE knowledge_lineage_derived (\n\tid SERIAL NOT NULL, \n\tknowledge_lineage_id UUID NOT NULL, \n\tderived_from_id UUID NOT NULL, \n\trole VARCHAR(50), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(knowledge_lineage_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(derived_from_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_kl_derived_from ON knowledge_lineage_derived (derived_from_id)",
    "CREATE INDEX ix_kl_derived_lineage ON knowledge_lineage_derived (knowledge_lineage_id)",
    "CREATE TABLE terrain_session_sampling (\n\tid SERIAL NOT NULL, \n\tterrain_session_id UUID NOT NULL, \n\tsampling_event_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(terrain_session_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(sampling_event_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_ts_sampling_event ON terrain_session_sampling (sampling_event_id)",
    "CREATE INDEX ix_ts_sampling_session ON terrain_session_sampling (terrain_session_id)",
    "CREATE TABLE terrain_session_media (\n\tid SERIAL NOT NULL, \n\tterrain_session_id UUID NOT NULL, \n\tmedia_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(terrain_session_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(media_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_ts_media_media ON terrain_session_media (media_id)",
    "CREATE INDEX ix_ts_media_session ON terrain_session_media (terrain_session_id)",
    "CREATE TABLE data_subject_consent (\n\tid SERIAL NOT NULL, \n\tdata_subject_id UUID NOT NULL, \n\tconsent_id UUID NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(data_subject_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(consent_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_ds_consent_consent ON data_subject_consent (consent_id)",
    "CREATE INDEX ix_ds_consent_subject ON data_subject_consent (data_subject_id)",
    "CREATE TABLE outcome_evidence (\n\tid SERIAL NOT NULL, \n\toutcome_id UUID NOT NULL, \n\tevidence_id UUID NOT NULL, \n\trole VARCHAR(50) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(outcome_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(evidence_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_oe_evidence ON outcome_evidence (evidence_id)",
    "CREATE INDEX ix_oe_outcome ON outcome_evidence (outcome_id)",
    "CREATE TABLE model (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\ttype model_type NOT NULL, \n\tdescription TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_model_name ON model (name)",
    "CREATE INDEX ix_model_type ON model (type)",
    "CREATE TABLE model_run (\n\tid UUID NOT NULL, \n\tmodel_version_id UUID NOT NULL, \n\tscenario_id UUID, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\tstatus VARCHAR(20) NOT NULL, \n\tparameters JSONB NOT NULL, \n\tactivity_id UUID, \n\toutput_assertion_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(model_version_id) REFERENCES resource (id), \n\tFOREIGN KEY(scenario_id) REFERENCES resource (id), \n\tFOREIGN KEY(activity_id) REFERENCES resource (id), \n\tFOREIGN KEY(output_assertion_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_model_run_model_version_id ON model_run (model_version_id)",
    "CREATE INDEX ix_model_run_status ON model_run (status)",
    "CREATE TABLE dataset (\n\tid UUID NOT NULL, \n\ttitle VARCHAR(500) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tpublisher_id UUID, \n\tspatial_resolution VARCHAR(100), \n\ttemporal_resolution VARCHAR(100), \n\ttopic VARCHAR(200), \n\tpurpose dataset_purpose NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(publisher_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_dataset_title ON dataset (title)",
    "CREATE INDEX ix_dataset_topic ON dataset (topic)",
    "CREATE TABLE model_version (\n\tid UUID NOT NULL, \n\tmodel_id UUID NOT NULL, \n\tversion VARCHAR(50) NOT NULL, \n\trelease_date TIMESTAMP WITH TIME ZONE, \n\tchecksum VARCHAR(200), \n\tinputs_schema JSONB, \n\toutputs_schema JSONB, \n\ttrained_at TIMESTAMP WITH TIME ZONE, \n\tmetrics JSONB, \n\tfeature_set_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(model_id) REFERENCES resource (id), \n\tFOREIGN KEY(feature_set_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_model_version_model_id ON model_version (model_id)",
    "CREATE TABLE dataset_version (\n\tid UUID NOT NULL, \n\tdataset_id UUID NOT NULL, \n\tversion VARCHAR(50) NOT NULL, \n\trelease_date TIMESTAMP WITH TIME ZONE, \n\tchanges TEXT, \n\tstats JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(dataset_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_dataset_version_dataset_id ON dataset_version (dataset_id)",
    "CREATE TABLE data_asset (\n\tid UUID NOT NULL, \n\tdataset_version_id UUID NOT NULL, \n\tformat VARCHAR(50) NOT NULL, \n\tsize_bytes INTEGER NOT NULL, \n\tchecksum VARCHAR(200) NOT NULL, \n\tarchived_from UUID, \n\toriginal_uri VARCHAR(500), \n\tarchived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(dataset_version_id) REFERENCES resource (id), \n\tFOREIGN KEY(archived_from) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_data_asset_dataset_version_id ON data_asset (dataset_version_id)",
    "CREATE INDEX ix_data_asset_format ON data_asset (format)",
    "CREATE TABLE distribution (\n\tid UUID NOT NULL, \n\tdataset_version_id UUID NOT NULL, \n\taccess_method access_method NOT NULL, \n\taccess_url VARCHAR(500), \n\tlicence VARCHAR(100) NOT NULL, \n\trights_statement_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(dataset_version_id) REFERENCES resource (id), \n\tFOREIGN KEY(rights_statement_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_distribution_access_method ON distribution (access_method)",
    "CREATE INDEX ix_distribution_dataset_version_id ON distribution (dataset_version_id)",
    "CREATE TABLE feature (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tsource_type feature_source_type NOT NULL, \n\tcomputation_method TEXT, \n\tunit_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(unit_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_feature_name ON feature (name)",
    "CREATE TABLE feature_set (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tmodel_version_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(model_version_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_feature_set_name ON feature_set (name)",
    "CREATE TABLE inference (\n\tid UUID NOT NULL, \n\tmodel_version_id UUID NOT NULL, \n\tfeature_set_id UUID NOT NULL, \n\tinput_snapshot_id UUID, \n\toutput_assertion_id UUID, \n\tconfidence FLOAT NOT NULL, \n\tinferred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(model_version_id) REFERENCES resource (id), \n\tFOREIGN KEY(feature_set_id) REFERENCES resource (id), \n\tFOREIGN KEY(input_snapshot_id) REFERENCES resource (id), \n\tFOREIGN KEY(output_assertion_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_inference_model_version_id ON inference (model_version_id)",
    "CREATE TABLE observation (\n\tid UUID NOT NULL, \n\tsubject_id UUID NOT NULL, \n\tfeature_of_interest_id UUID, \n\tmethod_id UUID, \n\tinstrument_id UUID, \n\ttemporal_context_id UUID, \n\tsampling_effort JSONB, \n\tdetection_probability FLOAT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(subject_id) REFERENCES resource (id), \n\tFOREIGN KEY(feature_of_interest_id) REFERENCES resource (id), \n\tFOREIGN KEY(method_id) REFERENCES resource (id), \n\tFOREIGN KEY(instrument_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_observation_method_id ON observation (method_id)",
    "CREATE INDEX ix_observation_subject_id ON observation (subject_id)",
    "CREATE TABLE result (\n\tid UUID NOT NULL, \n\tobservation_id UUID NOT NULL, \n\tvalue_type value_type NOT NULL, \n\tvalue_numeric FLOAT, \n\tvalue_term_id UUID, \n\tvalue_text TEXT, \n\tunit_id UUID, \n\tuncertainty_id UUID, \n\tdetection_limit FLOAT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(observation_id) REFERENCES resource (id), \n\tFOREIGN KEY(value_term_id) REFERENCES resource (id), \n\tFOREIGN KEY(unit_id) REFERENCES resource (id), \n\tFOREIGN KEY(uncertainty_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_result_observation_id ON result (observation_id)",
    "CREATE TABLE method (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tprotocol_url VARCHAR(500), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_method_name ON method (name)",
    "CREATE TABLE instrument (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\ttype VARCHAR(100) NOT NULL, \n\tcalibration_date DATE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_instrument_type ON instrument (type)",
    "CREATE TABLE uncertainty (\n\tid UUID NOT NULL, \n\ttype uncertainty_type NOT NULL, \n\tlower FLOAT, \n\tupper FLOAT, \n\tconfidence_level FLOAT, \n\tdescription TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE TABLE quality_assessment (\n\tid UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tdimension quality_dimension NOT NULL, \n\tscore FLOAT NOT NULL, \n\tmethod VARCHAR(200) NOT NULL, \n\tassessed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(target_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_quality_assessment_target_id ON quality_assessment (target_id)",
    "CREATE TABLE activity (\n\tid UUID NOT NULL, \n\ttype activity_type NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\tagent_id UUID, \n\tmethod_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(agent_id) REFERENCES resource (id), \n\tFOREIGN KEY(method_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_activity_agent_id ON activity (agent_id)",
    "CREATE INDEX ix_activity_type ON activity (type)",
    "CREATE TABLE prov_entity (\n\tid UUID NOT NULL, \n\tchecksum VARCHAR(200), \n\tchecksum_algorithm VARCHAR(50), \n\twas_derived_from UUID, \n\twas_generated_by UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(was_derived_from) REFERENCES resource (id), \n\tFOREIGN KEY(was_generated_by) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_prov_entity_was_generated_by ON prov_entity (was_generated_by)",
    "CREATE TABLE agent (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\ttype agent_type NOT NULL, \n\torcid VARCHAR(50), \n\tror VARCHAR(50), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_agent_name ON agent (name)",
    "CREATE INDEX ix_agent_type ON agent (type)",
    "CREATE TABLE source (\n\tid UUID NOT NULL, \n\ttitle VARCHAR(500) NOT NULL, \n\tsubtype source_subtype NOT NULL, \n\tsource_nature source_nature NOT NULL, \n\turl VARCHAR(500), \n\tdoi VARCHAR(200), \n\tlicence VARCHAR(100), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_source_doi ON source (doi)",
    "CREATE INDEX ix_source_source_nature ON source (source_nature)",
    "CREATE INDEX ix_source_subtype ON source (subtype)",
    "CREATE TABLE citation (\n\tid UUID NOT NULL, \n\tsource_id UUID NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tcitation_role citation_role NOT NULL, \n\tlocator VARCHAR(100), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_id) REFERENCES resource (id), \n\tFOREIGN KEY(target_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_citation_source_id ON citation (source_id)",
    "CREATE INDEX ix_citation_target_id ON citation (target_id)",
    "CREATE TABLE entity (\n\tid UUID NOT NULL, \n\tentity_subtype VARCHAR(50), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_entity_entity_subtype ON entity (entity_subtype)",
    "CREATE TABLE entity_alias (\n\tid UUID NOT NULL, \n\tentity_id UUID NOT NULL, \n\tnamespace VARCHAR(50) NOT NULL, \n\texternal_id VARCHAR(200) NOT NULL, \n\texternal_url VARCHAR(500), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(entity_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_entity_alias_entity_id ON entity_alias (entity_id)",
    "CREATE INDEX ix_entity_alias_namespace ON entity_alias (namespace)",
    "CREATE TABLE concept (\n\tid UUID NOT NULL, \n\tpreferred_label VARCHAR(300) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tvocabulary_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(vocabulary_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_concept_vocabulary_id ON concept (vocabulary_id)",
    "CREATE TABLE concept_version (\n\tid UUID NOT NULL, \n\tconcept_id UUID NOT NULL, \n\trelease_id UUID, \n\tlabel VARCHAR(300) NOT NULL, \n\tfusions JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(concept_id) REFERENCES resource (id), \n\tFOREIGN KEY(release_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_concept_version_concept_id ON concept_version (concept_id)",
    "CREATE INDEX ix_concept_version_release_id ON concept_version (release_id)",
    "CREATE TABLE vocabulary (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tnamespace VARCHAR(100) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_vocabulary_namespace ON vocabulary (namespace)",
    "CREATE TABLE vocabulary_release (\n\tid UUID NOT NULL, \n\tvocabulary_id UUID NOT NULL, \n\tversion VARCHAR(50) NOT NULL, \n\trelease_date DATE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(vocabulary_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_vocabulary_release_vocabulary_id ON vocabulary_release (vocabulary_id)",
    "CREATE TABLE controlled_term (\n\tid UUID NOT NULL, \n\tvocabulary_id UUID NOT NULL, \n\tcode VARCHAR(100) NOT NULL, \n\tlabel VARCHAR(300) NOT NULL, \n\tparent_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(vocabulary_id) REFERENCES resource (id), \n\tFOREIGN KEY(parent_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_controlled_term_code ON controlled_term (code)",
    "CREATE INDEX ix_controlled_term_vocabulary_id ON controlled_term (vocabulary_id)",
    "CREATE TABLE instance (\n\tid UUID NOT NULL, \n\tconcept_id UUID NOT NULL, \n\tentity_id UUID, \n\tspatial_scope_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(concept_id) REFERENCES resource (id), \n\tFOREIGN KEY(entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_instance_concept_id ON instance (concept_id)",
    "CREATE INDEX ix_instance_entity_id ON instance (entity_id)",
    "CREATE TABLE question (\n\tid UUID NOT NULL, \n\ttext TEXT NOT NULL, \n\tquestion_type question_type NOT NULL, \n\tasked_by UUID, \n\tasked_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tscale_context_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(asked_by) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_question_question_type ON question (question_type)",
    "CREATE TABLE hypothesis (\n\tid UUID NOT NULL, \n\tquestion_id UUID NOT NULL, \n\ttext TEXT NOT NULL, \n\tstatus hypothesis_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(question_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_hypothesis_question_id ON hypothesis (question_id)",
    "CREATE INDEX ix_hypothesis_status ON hypothesis (status)",
    "CREATE TABLE decision (\n\tid UUID NOT NULL, \n\tquestion_id UUID, \n\tdecided_by UUID NOT NULL, \n\tdecision_text TEXT NOT NULL, \n\trationale TEXT NOT NULL, \n\tdecided_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tscale_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(question_id) REFERENCES resource (id), \n\tFOREIGN KEY(decided_by) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_decision_decided_by ON decision (decided_by)",
    "CREATE TABLE recommendation (\n\tid UUID NOT NULL, \n\tquestion_id UUID, \n\trecommended_by UUID NOT NULL, \n\trecommendation_text TEXT NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\tscale_context_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(question_id) REFERENCES resource (id), \n\tFOREIGN KEY(recommended_by) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id)\n)",
    "CREATE TABLE scenario (\n\tid UUID NOT NULL, \n\tname VARCHAR(300) NOT NULL, \n\tscenario_type scenario_type NOT NULL, \n\tscenario_subtype scenario_subtype, \n\tdescription TEXT NOT NULL, \n\tparameters JSONB NOT NULL, \n\tscale_context_id UUID, \n\ttemporal_context_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_scenario_name ON scenario (name)",
    "CREATE INDEX ix_scenario_scenario_type ON scenario (scenario_type)",
    "CREATE TABLE correlation (\n\tid UUID NOT NULL, \n\tmethod correlation_method NOT NULL, \n\tcoefficient FLOAT, \n\tstrength correlation_strength NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\tp_value FLOAT, \n\tevidence_assessment_id UUID, \n\tscale_context_id UUID, \n\tspatial_scope_id UUID, \n\ttemporal_context_id UUID, \n\tlifecycle_status lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(evidence_assessment_id) REFERENCES resource (id), \n\tFOREIGN KEY(scale_context_id) REFERENCES resource (id), \n\tFOREIGN KEY(spatial_scope_id) REFERENCES resource (id), \n\tFOREIGN KEY(temporal_context_id) REFERENCES resource (id)\n)",
    "CREATE TABLE capability (\n\tid UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tcapability_type capability_type NOT NULL, \n\tprovider_type provider_type NOT NULL, \n\tprovider_id UUID NOT NULL, \n\tinput_schema JSONB, \n\toutput_schema JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(provider_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_capability_capability_type ON capability (capability_type)",
    "CREATE INDEX ix_capability_name ON capability (name)",
    "CREATE INDEX ix_capability_provider_id ON capability (provider_id)",
    "CREATE TABLE unit (\n\tid UUID NOT NULL, \n\tsymbol VARCHAR(20) NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tucum_code VARCHAR(50), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_unit_symbol ON unit (symbol)",
    "CREATE TABLE place (\n\tid UUID NOT NULL, \n\tgeometry geometry(GEOMETRY,2154), \n\tsrid INTEGER NOT NULL, \n\tlabel VARCHAR(300), \n\tarea_m2 FLOAT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX idx_place_geometry ON place USING gist (geometry)",
    "CREATE INDEX ix_place_label ON place (label)",
    "CREATE TABLE temporal_context (\n\tid UUID NOT NULL, \n\tvalid_time_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\tvalid_time_end TIMESTAMP WITH TIME ZONE, \n\ttransaction_time_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttransaction_time_end TIMESTAMP WITH TIME ZONE, \n\tgranularity temporal_granularity NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE TABLE media (\n\tid UUID NOT NULL, \n\ttype media_type NOT NULL, \n\turl VARCHAR(500) NOT NULL, \n\tmime_type VARCHAR(100) NOT NULL, \n\tchecksum VARCHAR(200), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE\n)",
    "CREATE INDEX ix_media_type ON media (type)",
    "CREATE TABLE revision (\n\tid SERIAL NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tversion INTEGER NOT NULL, \n\tauthor_id UUID, \n\tjustification TEXT NOT NULL, \n\tparent_id INTEGER, \n\tvalid_time_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\tvalid_time_end TIMESTAMP WITH TIME ZONE, \n\ttransaction_time TIMESTAMP WITH TIME ZONE NOT NULL, \n\tactivity_id UUID, \n\tdiff_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(target_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(author_id) REFERENCES resource (id), \n\tFOREIGN KEY(parent_id) REFERENCES revision (id), \n\tFOREIGN KEY(activity_id) REFERENCES resource (id), \n\tFOREIGN KEY(diff_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_revision_target_id ON revision (target_id)",
    "CREATE INDEX ix_revision_target_version ON revision (target_id, version)",
    "CREATE TABLE confidence_graph (\n\tid UUID NOT NULL, \n\troot_resource_id UUID NOT NULL, \n\tconfidence_score FLOAT, \n\tpropagation_method propagation_method NOT NULL, \n\tsource_nodes JSONB NOT NULL, \n\tpropagation_tree JSONB NOT NULL, \n\tcomputed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcomputed_by UUID, \n\tvalid_for_revision_id INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(root_resource_id) REFERENCES resource (id), \n\tFOREIGN KEY(computed_by) REFERENCES resource (id), \n\tFOREIGN KEY(valid_for_revision_id) REFERENCES revision (id)\n)",
    "CREATE INDEX ix_confidence_graph_root_resource_id ON confidence_graph (root_resource_id)",
    "CREATE TABLE fertility_class (\n\tid UUID NOT NULL, \n\tspecies_entity_id UUID NOT NULL, \n\tsite_index_model_id UUID NOT NULL, \n\tclass_label VARCHAR(100) NOT NULL, \n\tdominant_height_m FLOAT, \n\treference_age_years INTEGER NOT NULL, \n\tlower_bound_m FLOAT, \n\tupper_bound_m FLOAT, \n\tcalibration_region VARCHAR(200) NOT NULL, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_fertility_class_bounds_order CHECK (lower_bound_m IS NULL OR upper_bound_m IS NULL OR lower_bound_m <= upper_bound_m), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(species_entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(site_index_model_id) REFERENCES site_index_model (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_fertility_class_site_index_model_id ON fertility_class (site_index_model_id)",
    "CREATE INDEX ix_fertility_class_source_id ON fertility_class (source_id)",
    "CREATE INDEX ix_fertility_class_species_entity_id ON fertility_class (species_entity_id)",
    "CREATE TABLE station_observation (\n\tid UUID NOT NULL, \n\tplot_reference VARCHAR(200) NOT NULL, \n\tstation_type_id UUID, \n\tkey_path_followed TEXT, \n\ttopography_observed TEXT, \n\tsubstrate_observed TEXT, \n\thydromorphy_observed TEXT, \n\tindicator_flora_observed TEXT, \n\tavailable_water_capacity_mm FLOAT, \n\tavailable_water_capacity_method VARCHAR(300), \n\tdetermination_uncertainty TEXT, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_station_observation_uncertainty_when_undetermined CHECK (station_type_id IS NOT NULL OR determination_uncertainty IS NOT NULL), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(station_type_id) REFERENCES station_type (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_station_observation_plot_reference ON station_observation (plot_reference)",
    "CREATE INDEX ix_station_observation_source_id ON station_observation (source_id)",
    "CREATE INDEX ix_station_observation_station_type_id ON station_observation (station_type_id)",
    "CREATE TABLE silvicultural_rule (\n\tid UUID NOT NULL, \n\tsilvicultural_system_id UUID, \n\tspecies_entity_id UUID, \n\trequired_context TEXT NOT NULL, \n\ttrigger TEXT NOT NULL, \n\taction TEXT NOT NULL, \n\tintensity TEXT NOT NULL, \n\tevidence_level evidence_level NOT NULL, \n\thuman_validator VARCHAR(300), \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_silvicultural_rule_human_validation_required CHECK (status <> 'accepted' OR human_validator IS NOT NULL), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(silvicultural_system_id) REFERENCES silvicultural_system (id), \n\tFOREIGN KEY(species_entity_id) REFERENCES resource (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_silvicultural_rule_silvicultural_system_id ON silvicultural_rule (silvicultural_system_id)",
    "CREATE INDEX ix_silvicultural_rule_source_id ON silvicultural_rule (source_id)",
    "CREATE INDEX ix_silvicultural_rule_species_entity_id ON silvicultural_rule (species_entity_id)",
    "CREATE TABLE health_risk (\n\tid UUID NOT NULL, \n\tsubject_id UUID NOT NULL, \n\tdiagnostic_protocol_id UUID, \n\tsymptom_observed TEXT NOT NULL, \n\tsuspected_causal_agent VARCHAR(300), \n\tconfirmed_causal_agent VARCHAR(300), \n\tconfirmation_method TEXT, \n\tseverity health_risk_severity, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_id UUID NOT NULL, \n\tstatus lifecycle_status NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_health_risk_confirmation_requires_method CHECK (confirmed_causal_agent IS NULL OR confirmation_method IS NOT NULL), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(subject_id) REFERENCES resource (id), \n\tFOREIGN KEY(diagnostic_protocol_id) REFERENCES diagnostic_protocol (id), \n\tFOREIGN KEY(source_id) REFERENCES resource (id)\n)",
    "CREATE INDEX ix_health_risk_diagnostic_protocol_id ON health_risk (diagnostic_protocol_id)",
    "CREATE INDEX ix_health_risk_source_id ON health_risk (source_id)",
    "CREATE INDEX ix_health_risk_subject_id ON health_risk (subject_id)",
    "CREATE TABLE snapshot (\n\tid SERIAL NOT NULL, \n\ttarget_id UUID NOT NULL, \n\trevision_id INTEGER, \n\tcaptured_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tserialized_state JSONB NOT NULL, \n\tchecksum VARCHAR(200) NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(target_id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(revision_id) REFERENCES revision (id)\n)",
    "CREATE INDEX ix_snapshot_target_id ON snapshot (target_id)",
    "CREATE TABLE resource_diff (\n\tid UUID NOT NULL, \n\tfrom_revision_id INTEGER, \n\tto_revision_id INTEGER, \n\tchanges JSONB NOT NULL, \n\tsummary TEXT, \n\tfield_changes JSONB NOT NULL, \n\tadded_relations JSONB NOT NULL, \n\tremoved_relations JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES resource (id) ON DELETE CASCADE, \n\tFOREIGN KEY(from_revision_id) REFERENCES revision (id), \n\tFOREIGN KEY(to_revision_id) REFERENCES revision (id)\n)",
    "CREATE INDEX ix_resource_diff_to_revision_id ON resource_diff (to_revision_id)",
    "COMMENT ON COLUMN resource_diff.changes IS '{added: {...}, modified: {field: {from, to}}, removed: {...}}'",
)

_DOWNGRADE_STATEMENTS: tuple[str, ...] = (
    "DROP TABLE resource_diff",
    "DROP TABLE snapshot",
    "DROP TABLE health_risk",
    "DROP TABLE silvicultural_rule",
    "DROP TABLE station_observation",
    "DROP TABLE fertility_class",
    "DROP TABLE confidence_graph",
    "DROP TABLE revision",
    "DROP TABLE media",
    "DROP TABLE temporal_context",
    "DROP TABLE place",
    "DROP TABLE unit",
    "DROP TABLE capability",
    "DROP TABLE correlation",
    "DROP TABLE scenario",
    "DROP TABLE recommendation",
    "DROP TABLE decision",
    "DROP TABLE hypothesis",
    "DROP TABLE question",
    "DROP TABLE instance",
    "DROP TABLE controlled_term",
    "DROP TABLE vocabulary_release",
    "DROP TABLE vocabulary",
    "DROP TABLE concept_version",
    "DROP TABLE concept",
    "DROP TABLE entity_alias",
    "DROP TABLE entity",
    "DROP TABLE citation",
    "DROP TABLE source",
    "DROP TABLE agent",
    "DROP TABLE prov_entity",
    "DROP TABLE activity",
    "DROP TABLE quality_assessment",
    "DROP TABLE uncertainty",
    "DROP TABLE instrument",
    "DROP TABLE method",
    "DROP TABLE result",
    "DROP TABLE observation",
    "DROP TABLE inference",
    "DROP TABLE feature_set",
    "DROP TABLE feature",
    "DROP TABLE distribution",
    "DROP TABLE data_asset",
    "DROP TABLE dataset_version",
    "DROP TABLE model_version",
    "DROP TABLE dataset",
    "DROP TABLE model_run",
    "DROP TABLE model",
    "DROP TABLE outcome_evidence",
    "DROP TABLE data_subject_consent",
    "DROP TABLE terrain_session_media",
    "DROP TABLE terrain_session_sampling",
    "DROP TABLE knowledge_lineage_derived",
    "DROP TABLE correlation_variable",
    "DROP TABLE ecological_state_basis",
    "DROP TABLE experiment_model_run",
    "DROP TABLE experiment_scenario",
    "DROP TABLE feature_set_feature",
    "DROP TABLE recommendation_scenario",
    "DROP TABLE recommendation_assertion",
    "DROP TABLE decision_evidence",
    "DROP TABLE decision_recommendation",
    "DROP TABLE hypothesis_contradicting",
    "DROP TABLE hypothesis_supporting",
    "DROP TABLE conflict_cluster_assertion",
    "DROP TABLE model_run_output",
    "DROP TABLE model_run_input",
    "DROP TABLE botanical_identification_decision",
    "DROP TABLE botanical_identification_result",
    "DROP TABLE botanical_identification_request",
    "DROP TABLE conflict_cluster",
    "DROP TABLE spatial_disclosure_policy",
    "DROP TABLE sensitivity_classification",
    "DROP TABLE access_policy",
    "DROP TABLE rights_statement",
    "DROP TABLE provenance_material",
    "DROP TABLE diagnostic_protocol",
    "DROP TABLE silvicultural_system",
    "DROP TABLE station_type",
    "DROP TABLE site_index_model",
    "DROP TABLE autecology_profile",
    "DROP TABLE persistent_identifier",
    "DROP TABLE data_subject",
    "DROP TABLE consent",
    "DROP TABLE sample",
    "DROP TABLE trait_value",
    "DROP TABLE trait_definition",
    "DROP TABLE sampling_event",
    "DROP TABLE relation_type",
    "DROP TABLE ecological_process",
    "DROP TABLE phenomenon",
    "DROP TABLE scale_context",
    "DROP TABLE ecosystem_service",
    "DROP TABLE ecological_state",
    "DROP TABLE terrain_session",
    "DROP TABLE experiment",
    "DROP TABLE knowledge_lineage",
    'DROP TABLE "constraint"',
    "DROP TABLE goal",
    "DROP TABLE flow",
    "DROP TABLE diagnostic",
    "DROP TABLE administrative_unit",
    "DROP TABLE outcome_tracking",
    "DROP TABLE compliance_check",
    "DROP TABLE regulation",
    "DROP TABLE economic_scenario",
    "DROP TABLE intervention",
    "DROP TABLE management_plan",
    "DROP TABLE evidence_assessment",
    "DROP TABLE predicate",
    "DROP TABLE assertion_qualifier",
    "DROP TABLE assertion_participant",
    "DROP TABLE assertion",
    "DROP TABLE inbox_event",
    "DROP TABLE outbox_event",
    "DROP TABLE resource",
    "DROP TYPE claim_kind",
    "DROP TYPE lifecycle_status",
    "DROP TYPE rule_subtype",
    "DROP TYPE participant_role",
    "DROP TYPE evidence_level",
    "DROP TYPE management_plan_type",
    "DROP TYPE plan_status",
    "DROP TYPE intervention_type",
    "DROP TYPE intervention_status",
    "DROP TYPE economic_category",
    "DROP TYPE regulation_domain",
    "DROP TYPE compliance_status",
    "DROP TYPE outcome_status",
    "DROP TYPE administrative_level",
    "DROP TYPE diagnostic_type",
    "DROP TYPE diagnostic_global_state",
    "DROP TYPE diagnostic_validation_status",
    "DROP TYPE flow_type",
    "DROP TYPE flow_direction",
    "DROP TYPE propagation_method",
    "DROP TYPE goal_type",
    "DROP TYPE goal_priority",
    "DROP TYPE constraint_type",
    "DROP TYPE constraint_severity",
    "DROP TYPE terrain_session_type",
    "DROP TYPE sync_status",
    "DROP TYPE state_type",
    "DROP TYPE ecological_grade",
    "DROP TYPE trend",
    "DROP TYPE ecosystem_service_category",
    "DROP TYPE scale_level",
    "DROP TYPE phenomenon_type",
    "DROP TYPE ecological_process_type",
    "DROP TYPE relation_category",
    "DROP TYPE sample_type",
    "DROP TYPE consent_scope",
    "DROP TYPE legal_basis",
    "DROP TYPE pid_type",
    "DROP TYPE silvicultural_system_category",
    "DROP TYPE health_risk_severity",
    "DROP TYPE materiel_base_category",
    "DROP TYPE usage_rights",
    "DROP TYPE permission",
    "DROP TYPE sensitivity_level",
    "DROP TYPE conflict_status",
    "DROP TYPE identification_decision_status",
    "DROP TYPE model_type",
    "DROP TYPE dataset_purpose",
    "DROP TYPE access_method",
    "DROP TYPE feature_source_type",
    "DROP TYPE value_type",
    "DROP TYPE uncertainty_type",
    "DROP TYPE quality_dimension",
    "DROP TYPE activity_type",
    "DROP TYPE agent_type",
    "DROP TYPE source_subtype",
    "DROP TYPE source_nature",
    "DROP TYPE citation_role",
    "DROP TYPE question_type",
    "DROP TYPE hypothesis_status",
    "DROP TYPE scenario_type",
    "DROP TYPE scenario_subtype",
    "DROP TYPE correlation_method",
    "DROP TYPE correlation_strength",
    "DROP TYPE capability_type",
    "DROP TYPE provider_type",
    "DROP TYPE temporal_granularity",
    "DROP TYPE media_type",
)


def _executer(statements: tuple[str, ...]) -> None:
    for statement in statements:
        op.execute(statement)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS age")
    op.execute("LOAD 'age'")
    op.execute("SET search_path = public, ag_catalog, tiger")
    op.execute("SELECT create_graph('gsie_knowledge_graph')")
    _executer(_UPGRADE_STATEMENTS)


def downgrade() -> None:
    _executer(_DOWNGRADE_STATEMENTS)
    op.execute("LOAD 'age'")
    op.execute("SET search_path = public, ag_catalog, tiger")
    op.execute("SELECT drop_graph('gsie_knowledge_graph', true)")
